### PR TITLE
Disable timeout params for deleteIndex API only for serverless

### PR DESCRIPTION
**Pull request by ykmr1224**
### Description
- Disable timeout params for deleteIndex API only for serverless
- OpenSearch serverless does not accept `timeout` / `master_timeout` (= clusterManagerNodeTimeout) params, which is added by the RestHighLevelClient by default. (current version of `opensearch-java` library won't add it automatically, but we are still using `2.6.0` ([ref](https://github.com/opensearch-project/opensearch-spark/blob/fd3f82fc16273d47f17aa47e699aeaa8b4c3679d/build.sbt#L13-L15))

### Issues Resolved
https://github.com/opensearch-project/opensearch-spark/issues/634

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by noCharger — COMMENTED** [review]
non-blocking: can we handle this in RestHighLevelClientWrapper and consider use DeleteIndexRequestBuilder?

**Comment by ykmr1224** [comment]
> non-blocking: can we handle this in RestHighLevelClientWrapper and consider use DeleteIndexRequestBuilder?

RestHighLevelClientWrapper does not have reference to FlintOptions.
What do you mean by DeleteIndexRequestBuilder?

**Comment by noCharger** [comment]
> > non-blocking: can we handle this in RestHighLevelClientWrapper and consider use DeleteIndexRequestBuilder?
> 
> RestHighLevelClientWrapper does not have reference to FlintOptions. What do you mean by DeleteIndexRequestBuilder?

Example:

```
public void deleteIndex(String indexName) {
    LOG.info("Deleting Flint index " + indexName);
    String osIndexName = sanitizeIndexName(indexName);
    try (IRestHighLevelClient client = createClient()) {
        DeleteIndexRequest request = buildDeleteIndexRequest(osIndexName);
        client.indices().delete(request, RequestOptions.DEFAULT);
    } catch (Exception e) {
        throw new IllegalStateException("Failed to delete Flint index " + osIndexName, e);
    }
}

private DeleteIndexRequest buildDeleteIndexRequest(String indexName) {
    DeleteIndexRequestBuilder builder = new DeleteIndexRequestBuilder(indexName);

    if (FlintOptions.SERVICE_NAME_AOSS.equals(options.getServiceName())) {
        // Disable timeouts for serverless environments
        builder.setClusterManagerNodeTimeout((TimeValue) null)
               .setTimeout((TimeValue) null);
    }

    return builder.build();
}

```

**Review by seankao-az — APPROVED** [review]
lgtm
+1 on Louis' idea on moving `new DeleteIndexRequest(osIndexName)` into build method.
but don't think it's necessary

**Comment by ykmr1224** [comment]
I think current approach is more explicit and easier to read, though there could be some preference.

**Comment by noCharger** [comment]
> I think current approach is more explicit and easier to read, though there could be some preference. btw, `DeleteIndexRequestBuilder` does not look like usable considering the constructor signature: `public DeleteIndexRequestBuilder(OpenSearchClient client, DeleteIndexAction action, String... indices)`

Actually, the DeleteIndexRequestBuilder from the library does not appear to be for external use; using the builder pattern externally is possible by extending it, but it is fine to leave it as is.

**Pull request merged**
