### PR TITLE
Fix refresh policy back to WAIT_FOR other than writing query result

### PR DESCRIPTION
**Pull request by ykmr1224**
### Description
- Fix refresh policy back to WAIT_FOR other than writing query result
- Those are fixed in #530 , but should not be changed since it could break due to eventual consistency. In actual use case, AOSS doesn't need to write to other than result and index(MV/CV/SK)

### Issues Resolved
_List any issues this PR will resolve, e.g. Closes [...]._ 

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by dai-chen — APPROVED** [review]
Just to confirm: my understanding is we need to make sure refresh policy is set to `WAIT_FOR` in Spark job before we deploy this in Flint 0.5, right? Otherwise, the refresh policy of writing to result index becomes `NONE`?

**Comment by ykmr1224** [comment]
> Just to confirm: my understanding is we need to make sure refresh policy is set to `WAIT_FOR` in Spark job before we deploy this in Flint 0.5, right? Otherwise, the refresh policy of writing to result index becomes `NONE`?

That's right.

**Review by penghuo — APPROVED** [review]

**Comment by noCharger** [comment]
QQ: why it takes longer after this change? Previously it was around 40-45 mins and now it's around 1 hour

**Review by noCharger — COMMENTED** [review]
QQ: why it takes longer after this change? Previously it was around 40-45 mins and now it's around 1 hour

**Pull request merged**
