### PR TITLE
update MAINTAINERS.md

### PR DESCRIPTION
**Pull request by YANG-DB**
### Description
update MAINTAINERS.md to reflect recently added maintainer

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by YANG-DB** [comment]
@penghuo @noCharger @penghuo @dai-chen Please approve
thanks

**Review by noCharger — COMMENTED** [review]
could you also update https://github.com/opensearch-project/opensearch-spark/blob/main/.github/CODEOWNERS based on MAINTAINERS.md?

**Review by penghuo — APPROVED** [review]
Thx!

**Comment by YANG-DB** [comment]
> could you also update https://github.com/opensearch-project/opensearch-spark/blob/main/.github/CODEOWNERS based on MAINTAINERS.md?

I think it's only valid for members of the opensearch org

**Pull request merged**
