### PR TITLE
Upgrade Spark 3.5.1

### PR DESCRIPTION
**Pull request by penghuo**
### Description

Merge [feature bracnh spark-3.5.1](https://github.com/opensearch-project/opensearch-spark/tree/spark-3.5.1).

### Test
```
sbt integtest/awsIntegration

[info] Run completed in 3 minutes, 13 seconds.
[info] Total number of tests run: 2
[info] Suites: completed 2, aborted 0
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
```

### Perf Test - direct query
Compared to Spark 3.3 (EMR-S 6.10), there is no significant difference observed.

output (1)

|   id |   emrs-p90 |   query-p90 |
|-----:|-----------:|------------:|
|    1 |    347.619 |     169.222 |
|    2 |    256.612 |     151.244 |
|    3 |    241.754 |     148.445 |
|    4 |    196.452 |     110.116 |
|    5 |    257.463 |     164.604 |
|    6 |    286.919 |     175.081 |
|    7 |    317.325 |     219.362 |
|    8 |    256.688 |     153.681 |
|    9 |    257.500 |     153.506 |
|   10 |    256.969 |     155.818 |
|   11 |    256.854 |     160.758 |
|   12 |    286.868 |     190.403 |
|   13 |    256.809 |     153.911 |
|   14 |    271.859 |     167.041 |
|   15 |    317.254 |     217.635 |
|   16 |    332.309 |     225.800 |
|   17 |    241.652 |     149.872 |
|   18 |    256.916 |     146.927 |
|   19 |    242.132 |     139.627 |
|   20 |    287.283 |     182.994 |

### Issues Resolved
https://github.com/opensearch-project/opensearch-spark/issues/352

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by LantaoJin — APPROVED** [review]
LGTM

**Review by YANG-DB — APPROVED** [review]

**Comment by dai-chen** [comment]
**Leave this PR as is for author to decide whether to squash or not.**

**Review by dai-chen — APPROVED** [review]
**Leave this PR as is for author to decide if squash or not.**

**Review by noCharger — APPROVED** [review]
Thx for change. Any data can be shared for the below?

```
 Performance test
 Direct SparkSQL query performance
 Flint index building performance, including skipping/CV/MV
 Query acceleration performance, including skipping/CV
```

**Pull request merged**
